#!/bin/bash

EXTS="cpp hpp h c cc cxx hxx py def js styl jade pug s S F90 f90 i f F cu cuh "
EXTS+=" tpl vue"
FOLLOW=
declare -a DIRS

usage() {
    echo "Usage: $1 [OPTIONS]"
    echo "  -L              Follow symbolic links."
    echo "  -D <dir>        Search in this directory."
    echo "  -E <exts>       Search for these file extensions. (default = $EXTS)"
    echo "  --help          Show this help screen and exit."
}

while [ "$1" != "" ]; do
    case "$1" in
        -L) FOLLOW=-L ;;
        -D)
            shift
            DIRS[${#DIRS[*]}]="$1"
            ;;

        -E)
            shift
            EXTS="$1"
            ;;

        --help)
            usage "$0"
            exit 0
            ;;

        *)
            usage "$0"
            echo -e "\nERROR: Invalid option '$1'"
            exit 1
            ;;
    esac
    shift
done


OPTS=
for i in $EXTS; do
    if [ "$OPTS" != "" ]; then
        OPTS="$OPTS -o"
    fi
    OPTS="$OPTS -iname \*.$i"
done

if [ ${#DIRS[*]} -eq 0 ]; then
  DIRS[${#DIRS[*]}]="."
fi

for DIR in ${DIRS[@]}; do
  eval find $FOLLOW "$DIR" \\\( $OPTS \\\) -a -type f
done
